### ISSUE TITLE
Monitor does not compute Extension Settings Data Element values

### ISSUE THREAD

**Issue by anada10** [adobe/reactor-turbine#127]
This issue references the Monitor debugging feature of Adobe Launch [found here](https://experienceleague.adobe.com/docs/launch/using/client-side-info/launch-object-reference.html?lang=en#monitor).

### Expected Behaviour
When logging a rules extension settings, we expect `_satellite._monitors` to evaluate data element values

_This is an example of a computed data element_
![image](https://user-images.githubusercontent.com/47853125/120959833-fdfde580-c79d-11eb-914f-122a0b98adaa.png)

### Actual Behaviour
When logging a rules extension settings, `_satellite._monitors` does not evaluate the data element value only the data element name eg `%constantTest%` as opposed to `testValue1`. (see image)

_This is an example of `_satellite._monitors` not evaluating data elements in a rule component's settings for an Adobe Analytics Set Variables Action._ 
![image](https://user-images.githubusercontent.com/47853125/120959300-c5a9d780-c79c-11eb-835c-92b6c460d89d.png)

_This behaviour is consistent for any settings, eg Google Ads Tack Conversion action settings below_ 
![image](https://user-images.githubusercontent.com/47853125/120961134-8c736680-c7a0-11eb-9d4c-e6b912de1e0b.png)

### Reproduce Scenario (including but not limited to)

1. Go to getmonita.io and open the console
2. Ensure you can see the _monitors logging events (eg rule completed, rule triggered) for different rules
3. Check the monitors logs _ruleCompleted_ for the rule: _Set Variables Adobe Analytics_monita_
4. Drill down to `actions[0].settings.trackerProperties.eVars[0].value`
5. Results
**Expected:** `testValue1`
**Actual:** `%constantTest%` (as in image above)

#### Steps to Reproduce
1. Setup a test website with an adobe launch client side property with the following included:
- Add `_satellite._monitors` logging on page ([use this article to setup](https://experienceleague.adobe.com/docs/launch/using/client-side-info/launch-object-reference.html?lang=en#monitor))
- Add Adobe Analytics Extension
- Create a Data Element with name **DE Test** of type Constant with value: `testValue1` 
- Create a Rule
**Rule Name:** Data Element Test  
**Event:** Core - DOM Ready
**Action:** Adobe Analytics - Set Variables. 
Add the Data Element in various parts of the set variables settings, eg in evars, props etc
2. Save Rule
3. Create and Build Library
4. Open console in Chrome and go to the test website
5. Check the monitors logs _ruleCompleted_ for the rule: _Data Element Test_
6. Drill down to `actions[0].settings.trackerProperties.eVars[0].value`
7. Results
**Expected:** `testValue1`
**Actual:** `%DE Test%` (assuming we both have the same result, else let us know 😃  )

#### Platform and Version
Adobe Launch Client Side
Core Extension v2.0.7
Adobe Analytics Extension v1.8.5
Chrome Version 91.0.4472.77 (Official Build) (x86_64) Mac

#### Sample Code that illustrates the problem
See above

#### Logs taken while reproducing problem
N/A

**Comment by thebenrob** [comment]
@adobe export issue to Jira project PDCL

**Comment by jeffreywalter** [comment]
Unfortunately, the impact for the incorporating this kind of change would impact performance too much. This would require copying/managing settings during a session and is not feasible at this time.
